### ISSUE TITLE
Cannot update an specific field in a row.

### ISSUE THREAD

**Issue by victortyau** [yortus/DBFFile#11]
Hi mate, I am having some troubles about updating a specific field in the row, please check this example and help me.

the file has one row, I only want to update this two specific field in the first row, I will be waiting for your comments 

var rows = [{
  ULTSOCIO:'3223',
  ULTAHORROS: '8889'
}];

DBFFILE.open('NUMETRAN.DBF')
  .then(dbf => {

    dbf
    return dbf.set(rows);
})
.catch(err => console.log('An error occurred: ' + err));

**Comment by yortus** [comment]
Hi @victortyau, 

This library only supports appending records at the moment. What you could do in this case is read the row from the .dbf file, then create a temporary .dbf file and append the updated row to it, then copy the temporary file back over the original file.

For updating rows directly, a PR would be welcomed. I can't remember why that wasn't implemented (I haven't used this in a while), but I suspect it was simply not a use case we needed at the time.
