### ISSUE TITLE
Search DBF by key

### ISSUE THREAD

**Issue by kalihos** [yortus/DBFFile#13]
Hello.

I'm trying to get a specific record from the database, not the whole file. Is it possible to get, for example, column NAME whose ID = 10657? I say, something "SQL style". I am receiving a person's ID, and I want to know his card ID.

Thank you very much in advance.

**Comment by yortus** [comment]
Sorry, this lib doesn't include any query functionality. You'd have to add that in your own code.

I think if any query functionality was going to be added in here, it would make sense to be a subset of SQL. But that's a pretty big project on its own.

**Comment by kalihos** [comment]
Hi Troy.

Thanks a lot for your answer. I have tried reading sequentially, and the
performance is great anyway.


2018-01-06 5:44 GMT+01:00 Troy Gerwien <notifications@github.com>:
