### ISSUE TITLE
save file error

### ISSUE THREAD

**Issue by fcpauldiaz** [yortus/DBFFile#14]
I get this error when I try to save a file.
`An error occurred: TypeError: fs.openAsync is not a function`
Here is my code
```js
 DBFFile.create(`Archivo - ${moment().format(format)}.dbf`, fieldDescriptors)
          .then(dbf => {
              console.log('DBF file created.');
              return dbf.append(rows);
          })
          .then(() => console.log(rows.length + ' rows added.'))
          .catch(err => console.log('An error occurred: ' + err));
```

**Comment by fcpauldiaz** [comment]
@yortus

**Comment by yortus** [comment]
Hi @fcpauldiaz sorry for the long delay.

I just did a fresh install and ran the tests and don't get any errors.

If this is still an issue for you, could you provide some steps I can follow to reproduce the error you are getting?

**Comment by fcpauldiaz** [comment]
I'm trying to save it from the browser, I'm not sure if that is supported.

**Comment by Seikho** [comment]
The browser doesn't have Node's `fs` module. You'll most likely need to use a server that exposes an API that performs the DB writes.

**Comment by fcpauldiaz** [comment]
Ok, thanks
