### ISSUE TITLE
how can i defined decoding type?

### ISSUE THREAD

**Issue by JesseWeb** [yortus/DBFFile#18]
needs gb2312 decoding dbf file,but get utf8

**Comment by yortus** [comment]
@JesseWeb have a look at [https://nodejs.org/api/buffer.html#buffer_buffers_and_character_encodings](https://nodejs.org/api/buffer.html#buffer_buffers_and_character_encodings). It doesn't look like Node.js supports gb2312?

**Comment by yortus** [comment]
Specifying character encodings is supported now in V1.0. 'gb2312' should work according to https://github.com/ashtuchkin/iconv-lite/wiki/Supported-Encodings.
