### ISSUE TITLE
Thai Character Support

### ISSUE THREAD

**Issue by smiley159** [yortus/DBFFile#21]
Hi, greeting from Thailand :) 

Can you please guide me to how to make this work with thai characters?
Everything else works perfect though.

**Comment by yortus** [comment]
Hi @smiley159, do you already have a DBF file with Thai characters in it? Do you know the encoding in the file? It is UTF8?

**Comment by smiley159** [comment]
Hi @yortus thank you for trying to help me out.
Yes I do have this dbf file. The encoding is TIS-620
Here is the file https://1drv.ms/u/s!AlnHvqI889h8g71otS53NOnz7CY4Cg

**Comment by smiley159** [comment]
I just managed to tangle your code a bit and find my way out! Thank you for your time any way :D. I really appreciate your work.

**Comment by yortus** [comment]
Thanks @smiley159. So did you solve your problem somehow, or are you still looking for support with this encoding issue? If you found a solution, it is something you think could be added to this library?

**Comment by yortus** [comment]
Hi @smiley159, encoding options are now oficially supported in V1.0.

**Comment by yortus** [comment]
By the way, I used the test file you linked above as a test fixture. Please let me know if this is a problem.
