### ISSUE TITLE
text cut off at halt when appendRecords with multi-byte encoding

### ISSUE THREAD

**Issue by mmagi** [yortus/DBFFile#23]
https://github.com/yortus/DBFFile/blob/5b82aaed1f8d0440f6540d53b7ec4bc3ee0d9d52/src/dbf-file.ts#L365
this line should be 
```js
let byte = k < b.length ? b[k] : 0x20;
```
instead of value.length

**Comment by yortus** [comment]
Thanks @mmagi! Should be fixed in v1.3.0.
