### ISSUE TITLE
Add support for Visual FoxPro tables & DateTime fields

### ISSUE THREAD

**Issue by lordrip** [yortus/DBFFile#25]
Hi! thanks for this nice library. I've wanted to ask, if is possible to add support to Visual FoxPro tables and DateTime fields. Currently I'm working on migrating some local VFP data to a web server. I'm working on it, can I make a PR for your consideration when is done?

Thanks in advanced!

**Comment by yortus** [comment]
Please Do! The info in the [docs directory](https://github.com/yortus/DBFFile/blob/master/doc/README.md) should help. The first link has the most info.

**Comment by lordrip** [comment]
Nice! I'll prepare it and send a PR, the format is very similar, the issue that I'm working on right now is how to properly format the DateTime field 👍
