### ISSUE TITLE
Cannot find typings for published v1.4

### ISSUE THREAD

**Issue by lordrip** [yortus/DBFFile#28]
After installing dbffile@1.4, vscode complaints about that cannot find typings of dbffile module.

**Comment by troyvgw** [comment]
Looks like the `.npmignore` file needs a `!*.d.ts` line right after the `*.ts` line. I'm not sure how this ever worked before.

I can't get to it right now but will publish a new version in the next couple of days.

**Comment by yortus** [comment]
Looks like the `.npmignore` file needs a `!*.d.ts` line right after the `*.ts` line. I'm not sure how this ever worked before.

It should be fixed now. Published an update in v1.4.1. Let me know if there are any problems.

**Comment by lordrip** [comment]
Cool, now it works like a charm, thanks and sorry for bothering again :D
