### ISSUE TITLE
Error on read large file

### ISSUE THREAD

**Issue by cardote** [yortus/DBFFile#29]
Hi, this error is happening when i try to read a large file (36k records)

{ [Error: EINVAL: invalid argument, read] errno: -4071, code: 'EINVAL', syscall: 'read' }

i cant find anything on google :(

**Comment by yortus** [comment]
Are you reading all the records in one call, or in smaller batches?

**Comment by cardote** [comment]
@yortus 
I tried both ways, read the file at once and split it, I split into 500 records and in another attempt split into 1000 records and in another attempt batches of 5000 records, they all failed when they reached 10000 read records.

**Comment by yortus** [comment]
If it always fails around the 10000 mark, could it be the contents of a specific record that is causing the failure? Also what kind of file is it? version 0x83? With/without memo?

**Comment by cardote** [comment]
the error was in the file, already solved, thanks for the help and thanks for the api
:D
