### ISSUE TITLE
How to create dbffile field type date (D (date))

### ISSUE THREAD

**Issue by sahaphon** [yortus/DBFFile#31]
I want create dbf file but error..
let fieldDesc = [
         { name: 'date', type: 'D', size: 8 }
];

and set value
let records = [
        { date: '12/12/19' }
    ];

**Comment by sahaphon** [comment]
Help me.

**Comment by yortus** [comment]
@sahaphon you just need to pass a `Date` object instead of a string. Eg:

```ts
let fieldDesc = [
    { name: 'date', type: 'D', size: 8 }
];
...
let records = [
    { date: new Date('2019-12-12') }
];
```
