### ISSUE TITLE
I have and error when i tried the example

### ISSUE THREAD

**Issue by roniel-rhack** [yortus/DBFFile#33]
index.ts:14:64 - error TS2345: Argument of type '{ name: string; type: string; size: number; }[]' is not assignable to parameter of type 'FieldDescriptor[]'.
  Type '{ name: string; type: string; size: number; }' is not assignable to type 'FieldDescriptor'.
    Types of property 'type' are incompatible.
      Type 'string' is not assignable to type '"C" | "N" | "F" | "L" | "D" | "I" | "M" | "T" | "B"'.

14     let dbf = await DBFFile.create('<full path to .dbf file>', fieldDescriptors);

**Comment by yortus** [comment]
The example works in JavaScript. TypeScript is more strict, so you'll need to add a type annotation to the `fieldDescriptors` declaration to satisfy the compiler, i.e. `let fieldDescriptors: FieldDescriptor[] = [...];`

Alternatively, you could not declare a `fieldDescriptors` variable at all and just pass them directly to the `create` method which will correctly infer the type, i.e.:

```ts
    /*...*/
    let dbf = await DBFFile.create('<full path to .dbf file>', [
        { name: 'fname', type: 'C', size: 255 },
        { name: 'lname', type: 'C', size: 255 }
    ]);
    /*...*/
```

Please feel free to re-open if you are still having trouble with it.

**Comment by roniel-rhack** [comment]
When I use your way:
 /*...*/
    let dbf = await DBFFile.create('<full path to .dbf file>', [
        { name: 'fname', type: 'C', size: 255 },
        { name: 'lname', type: 'C', size: 255 }
    ]);
    /*...*/
a new error appear:
TypeError: The "original" argument must be of type Function

./node_modules/dbffile/dist/utils.js
node_modules/dbffile/dist/utils.js:6
  3 | const fs = require("fs");
  4 | const util_1 = require("util");
  5 | /** Promisified version of fs.close. */
> 6 | exports.close = util_1.promisify(fs.close);
  7 | /** Promisified version of fs.open. */
  8 | exports.open = util_1.promisify(fs.open);
  9 | /** Promisified version of fs.read. */

I have no idea whats happenings here.

**Comment by roniel-rhack** [comment]
Sorry, I was trying to run the example on the client-side, I made an API and run fine.
 if you need help with this project I can help, maybe is a good idea to migrate the project to typescript. what do you think?

**Comment by yortus** [comment]
Hi @roniel-rhack, the project is already written in TypeScript - see the [`src/`](https://github.com/yortus/DBFFile/tree/master/src) directory.

The examples in the README are in JavaScript since not all users are using TypeScript.
