### ISSUE TITLE
Getting error (node:7468) UnhandledPromiseRejectionWarning: Error: Type '0' is not supported     at Object.validateFieldDescriptor (C:\chatbot\node_modules\dbffile\dist\field-descriptor.js:16:15)     at openDBF (C:\chatbot\node_modules\dbffile\dist\dbf-file.js:82:32)

### ISSUE THREAD

**Issue by amruta21** [yortus/DBFFile#38]
As I am currently using big dbf file so I am getting error as 

(node:7468) UnhandledPromiseRejectionWarning: Error: Type '0' is not supported
    at Object.validateFieldDescriptor (C:\chatbot\node_modules\dbffile\dist\field-descriptor.js:16:15)
    at openDBF (C:\chatbot\node_modules\dbffile\dist\dbf-file.js:82:32)

Why there is type 0??

**Comment by yortus** [comment]
Hi @amruta21, there is no field type '0' in a valid dbf file, so possibly the file is not a valid dbf file? Are you able to process this file with other programs that understand dbf files (eg Excel)? Are you able to post the file for further investigation?

**Comment by yortus** [comment]
Hi @amruta21, the latest version has ['loose' read mode](https://github.com/yortus/DBFFile#loose-read-mode) support which may solve this. I'll close for now since it's gone stale. Feel free to re-open if you are still having problems.
