### ISSUE TITLE
Uncaught TypeError: The "original" argument must be of type Function

### ISSUE THREAD

**Issue by ionut-badea** [yortus/DBFFile#43]
Do you know something about this error?

![Screenshot_20201104_115005](https://user-images.githubusercontent.com/20051018/98096511-84fb8000-1e94-11eb-8d6a-46485ed0c4bd.png)
![Screenshot_20201104_115206](https://user-images.githubusercontent.com/20051018/98096514-85941680-1e94-11eb-8cda-9ca21050c536.png)

**Comment by yortus** [comment]
It looks like one of those `fs.xxx` values passed to `promisify` in the [utils.ts](https://github.com/yortus/DBFFile/blob/master/src/utils.ts) file is not a function.

The `fs` module is part of node.js, and I see from your screenshots that you are using webpack to include DBFFile in a bundle. So my guess is that whatever the `fs` value is in the bundle, perhaps it's not compatible with node.js's `fs` module?

**Comment by ionut-badea** [comment]
Thank you, I managed to resolve the issue, it was my mistake. I am building a desktop app with electron and Vue and I was trying to load the DBFFile into Vue.js's plugins folder instead of load it into the background.ts.

**Comment by Zaphod-Beeblebrox** [comment]
> Thank you, I managed to resolve the issue, it was my mistake. I am building a desktop app with electron and Vue and I was trying to load the DBFFile into Vue.js's plugins folder instead of load it into the background.ts.

can you expand on this? I'm having a very similar issue (also a VUE electron app).  I'm not using typescript though.  I load dbffile as part of a library/function file (which is loaded by my background.js file) ...  have been chasing this issue for days.

**Comment by Zaphod-Beeblebrox** [comment]
> Thank you, I managed to resolve the issue, it was my mistake. I am building a desktop app with electron and Vue and I was trying to load the DBFFile into Vue.js's plugins folder instead of load it into the background.ts.

Just wanted to come back and say thanks for this note.  While my primary function library was being imported in background.js, I did include a few functions being imported directly into Vue components.  That was forcing dbffile to be imported on the browser side.    Took me forever to find, but your comment gave me the right direction to look.

thanks!
