### ISSUE TITLE
open client side

### ISSUE THREAD

**Issue by joefreire** [yortus/DBFFile#6]
Hi, how i can to open dbf file in client side, without upload?

**Comment by yortus** [comment]
That's beyond the scope of this project, but I think you could adapt this project's byte-twiddling source code to do what you want, once you've obtained the bytes of a DBF file using some of the newer browser APIs:
- [File](https://developer.mozilla.org/en/docs/Web/API/File)
- [FileReader](https://developer.mozilla.org/en-US/docs/Web/API/FileReader)
- [ArrayBuffer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer)
- [DataView](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView)
