### ISSUE TITLE
Update and delete records?

### ISSUE THREAD

**Issue by rmissier** [yortus/DBFFile#61]
How can I update and delete records?

**Comment by yortus** [comment]
Hey @rmissier, there's no API for updating or deleting records in-place. This lib isn't design to be a full DBMS for dbf files, which would involve far more complexity (eg updating index files, locking, etc). It is really just a batch tool for getting stuff out of old dbf files, eg for importing into a more modern system.

Having said that, it _is_ possible (although inconvenient) to update/delete records by batch-rewriting the whole dbf file.
