### ISSUE TITLE
Issue using with node project.

### ISSUE THREAD

**Issue by ghost** [yortus/DBFFile#66]
I get the following error when trying to use the module 

`App threw an error during load
C:\Users\desktop\testapp\main.js:12
import {DBFFile} from 'dbffile';
^^^^^^

SyntaxError: Cannot use import statement outside a module`

I am a beginner so I am sure this is user error.  What is the proper way to import this project?

**Comment by ghost** [comment]
Ok reading up about this and my issues seem to be with electron not supporting es Modules sadly.

**Comment by yortus** [comment]
Sounds like there's nothing actionable here @freeloader247? Feel free to re-open otherwise.
