### ISSUE TITLE
Unsupported version

### ISSUE THREAD

**Issue by kalihos** [yortus/DBFFile#7]
Hi.

I'm really interested in your parser, because it allows to define each field length individually. I need to append new registers to an existing database. However, the parser gives me the following message: "AssertionError: File 'FILENAME.DBF' has unknown/unsupported dBase version: -11.".

Is it possible to make it work?

Thank you very much.

**Comment by yortus** [comment]
Hi @kalihos, 

The code only supports limited versions as you've discovered (the ones we needed for our work). I don't have time to work on this, but the code is not very complex, so if anyone wants to take a look at supporting more versions, a PR would be very welcome.

**Comment by kalihos** [comment]
Hi @yortus,

Thank you very much. I could finally use a combination of two connectors (one for reading, one for writing in a new DBF), and it gave me no problems, so I close this.

Thanks again.
