### ISSUE TITLE
Support stream?

### ISSUE THREAD

**Issue by michaelmok2021** [yortus/DBFFile#71]
Does the library support stream eg 

```javascript
const readStream = fs.createReadString('\path to dbf file")
readStream.pipe('process a row in the dbf file")
```

**Comment by yortus** [comment]
Not currently, no. The API is batch-oriented, but you can set the batch size to 1 and process records one-by-one. I guess you could build a streaming interface over the batch API. I'd certainly consider a PR for that.

**Comment by yortus** [comment]
Streaming is now supported using async generators / for-await-of thanks to @acdibble. See the README for an example.
