### ISSUE TITLE
Type 'Y' is not supported

### ISSUE THREAD

**Issue by zhuzhuojiang** [yortus/DBFFile#77]
I got "Type 'Y' is not supported" Error to read a DBF. And I searched the Y field type by google, got https://stackoverflow.com/questions/33774148/get-fieldtype-of-dbf-file  .  There is one command mentioned "'Y' (currency)" .
Should we add this type and as the with "I (Interger)" parser?

**Comment by zhuzhuojiang** [comment]
Should be
`                        case 'Y':
                            value = buffer.readInt32LE(offset);
                            value = value / Math.pow(10, field.decimalPlaces);
                            offset += field.size;
                            break;`
in dbf-file.js

**Comment by yortus** [comment]
Hi @zhuzhuojiang, sorry for the delay. Would you consider preparing a PR to support the Y field type? There's already been some work done in #60 that could be a starting point. As I [noted there](https://github.com/yortus/DBFFile/pull/60#pullrequestreview-817118787), the PR would need to include some unit tests, and support for both reading and writing.

**Comment by yortus** [comment]
'Y' type is now supported in v1.10.0
