### ISSUE TITLE
Long text fields breaking code

### ISSUE THREAD

**Issue by zoozalp** [yortus/DBFFile#80]
I had an issue with a super-old (from 90s) dbf file. Developer created a 256 characters long text field. I didn't notice the real issue since I was using loose read-mode.

I've just changed a few lines to walk around it. It's a little quick and dirty solution but it works for me. I'll post a pull request just in case anyone needs it.

**Comment by zoozalp** [comment]
You can also use patch-package until this pull request is approved.

[dbffile+1.9.2.patch](https://github.com/yortus/DBFFile/files/11857766/dbffile%2B1.9.2.patch)

**Comment by yortus** [comment]
Closing as stale, feel free to re-open if there's something new comes up.
