### ISSUE TITLE
readRecords(10) reads 10 first records. Can we add sort so that it reads 10 last records?

### ISSUE THREAD

**Issue by meilechwieder** [yortus/DBFFile#85]
I'm working with a DBF file that has 100's of 1000's of records. Whenever I want to read the last added records, I need to do `dbf.readRecords(Infinity)` and then `.revers()`.

It makes our application really slow.

Is there anyway to pass a sort option?

**Comment by yortus** [comment]
Hi @meilechwieder, sorry for the delay.

It sounds like you are trying to use this as a database driver for a running application? The purpose of this library is more for bulk extraction or rewrites, for scenarios like transferring data over to a new system.

Having said that, you could try adding a method to seek to a specific record index and then read records from there. Bear in mind though that DBF files may have deleted records at any position, so seeking to `recordCount - 10` and then reading the rest may give less than 10 records. But it should speed up your app.
