### ISSUE TITLE
Out of bounds error when reading records from VFPwMemo

### ISSUE THREAD

**Issue by jhrncar** [yortus/DBFFile#87]
Hello,
i am working on a tool that uses this library to open DBF files.
I have a dbf file with its fpt file in the same directory. The DBFFile.open works, the object is created:
![image](https://github.com/yortus/DBFFile/assets/71822106/7d2f45dd-b20d-49c5-ba87-bf7def1ef9e9)
As you can see, it correctly linked the files together and interpreted the field types.
However, when i attempt to read records from it, apparently the function accesses wrong memory blocks:
![image](https://github.com/yortus/DBFFile/assets/71822106/00907622-2c17-4b53-a567-5bd31a4dfde6)
I think it refers to this part of the code:
![image](https://github.com/yortus/DBFFile/assets/71822106/b255b9db-0000-426e-863f-02eff01d4e82)

Is it a bug, or am I doing something wrong?
Thanks for answers and help in advance <3 this library has been a life-saver

**Comment by jhrncar** [comment]
I have found the problem and it is not a bug in the library, rather than a missing feature lets say. Apparently, there is a feature in VFP9 that you can set blocksize to 0, which sets it to 1 byte. This lets save space, as there is minimal overhead for each of the fields. I have found this to be the case while extensive browsing and i came across this, which seems to be the official documentation: https://www.vfphelp.com/help/html/74f53aef-fd56-4f1a-a413-4f045922db21.htm
It stays the setting blocksize to 0.


Then, I came across this article: http://portal.dfpug.de/dfpug/Dokumente/FoxTalk/FoxTalk1996/FT19961_11.PDF
And i will save it here, if it ever goes away [FT19961_11.pdf](https://github.com/user-attachments/files/15903061/FT19961_11.pdf)
![image](https://github.com/yortus/DBFFile/assets/71822106/9ac93074-eedd-4c95-83b4-96e45f94d61d)
Will make a PR with this feature implemented, hopefully.

**Comment by lordrip** [comment]
Thanks for sharing this @jhrncar, today I learned :)

**Comment by jhrncar** [comment]
> Thanks for sharing this @jhrncar, today I learned :)

No problem, pleasure! I think I have something working, I am testing it. Probably will make a PR tomorrow (friday). Is it okay for you? Anything I should consider or some notes from you?

**Comment by yortus** [comment]
Thanks for investigating this @jhrncar! In terms of PR requirements:
* Your code fix for reading memos, in the same style as the surrounding code
* No need to consider writing memos as that isn't currently supported by the library
* At *least* one test case that fails without your fix and passes with your fix

The test case is quite important to verify the fix and prevent future regressions. However it will likely require a new test fixture to be added in the form of a dbf/fpt file with a memo field with 0 block size. Are you able to provide a suitable fixture? Obviously as this project is open source, it will need to be something that can be shared publicly.

**Comment by jhrncar** [comment]
> Thanks for investigating this @jhrncar! In terms of PR requirements:
> 
> * Your code fix for reading memos, in the same style as the surrounding code
> * No need to consider writing memos as that isn't currently supported by the library
> * At _least_ one test case that fails without your fix and passes with your fix
> 
> The test case is quite important to verify the fix and prevent future regressions. However it will likely require a new test fixture to be added in the form of a dbf/fpt file with a memo field with 0 block size. Are you able to provide a suitable fixture? Obviously as this project is open source, it will need to be something that can be shared publicly.

Thanks for the write up, I expected asa much. Will verify with my boss as this is cadastre data. The DBF/FPT itself I dont think holds any sensitive data, but from the nature of it being a cadastral file, it may be private, or at very least there may be a goodwill - no need to be private about it, but it shouldnt be uploaded on wide internet. Will check

**Comment by jhrncar** [comment]
> Thanks for investigating this @jhrncar! In terms of PR requirements:
> 
> * Your code fix for reading memos, in the same style as the surrounding code
> * No need to consider writing memos as that isn't currently supported by the library
> * At _least_ one test case that fails without your fix and passes with your fix
> 
> The test case is quite important to verify the fix and prevent future regressions. However it will likely require a new test fixture to be added in the form of a dbf/fpt file with a memo field with 0 block size. Are you able to provide a suitable fixture? Obviously as this project is open source, it will need to be something that can be shared publicly.

I talked about this wih my boss, unfortunately the law is such that the files cannot be used for use cases unrelated to the cadastre :(

**Comment by yortus** [comment]
Ok that's a pity, but understandable. Still raise the PR if you can. Maybe we can find or make a fixture somehow.

**Comment by jhrncar** [comment]
Yes, will do it either today or over the weekend

**Comment by jhrncar** [comment]
> Ok that's a pity, but understandable. Still raise the PR if you can. Maybe we can find or make a fixture somehow.

PR opened

**Comment by yortus** [comment]
Fixed by #88, thanks @jhrncar
