### ISSUE TITLE
FoxPro 2.x with memo (0xF5 version) support

### ISSUE THREAD

**Issue by jhrncar** [yortus/DBFFile#89]
Hello, as stated in #64 , I would like to see this support added as it once again helps us in our work product. The changes in the old PR I believe are still sufficient, I have done my own testing on our files (which are under NDA :( ) and it works well.

**Comment by jhrncar** [comment]
Okay, there seems to be one or two more instances of changes needed in the code, but I believe I have found them by try-fail method. If I find any documentation like last time, I will post it. In the last document about blocksize, it also states this version of DBF, so this is applicable here as well
![image](https://github.com/user-attachments/assets/3f29ec8f-4fbf-4f55-84f7-49b560145bcf)

**Comment by yortus** [comment]
Hi @jhrncar. If you are able to make a PR will all the required changes I'm open to accepting it. I can try to create a fixture manually like I did for #88. Just please be patient with review/merging as I will not be able to work on this for the next few weeks, but will definitely get to it after that.

**Comment by jhrncar** [comment]
> Hi @jhrncar. If you are able to make a PR will all the required changes I'm open to accepting it. I can try to create a fixture manually like I did for #88. Just please be patient with review/merging as I will not be able to work on this for the next few weeks, but will definitely get to it after that.

Hi, thanks for the response! Yes, will create the fixture. I have forked the repository and will implement the fix and test it on our data, if it passes the tests we will use the fix in production and can report to you with findings. First thing I found is that you cant just add || version == 0xf5 where 0x30 is... in one spot, where block index is calculated, this version needs to be decoded from string and not read as int from bytes. But everywhere else, it seems fine to just add || 0xf5

**Comment by jhrncar** [comment]
Hi @yortus , I didn't forget about this, I have implemented a fix at work and we have been testing it (along with other features of the project) and it seems it is working without problems. If all goes well, will create PR this week.

**Comment by yortus** [comment]
Thanks for the PR @jhrncar! I'm blocked timewise for a while, but I should have time to review and merge it next week.

**Comment by yortus** [comment]
#90 merged and published as v1.12.0. Thanks @jhrncar
